### ISSUE TITLE
Nmap Index not showing on management console

### ISSUE THREAD

**Issue by estoycon** [marco-lancini/docker_offensive_elk#2]
Having an issue with the index that was created using the command
`curl -XPUT 'localhost:9200/nmap-vuln-to-es'`
not showing up in the management console. 
Checking the indices via curl gave this result
`curl -X GET 'localhost:9200/_cat/indices?v'
health status index           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   nmap-vuln-to-es OUn7TnHkQ42bhXwstSjAuw   5   1          0            0      1.2kb          1.2kb`

Yet pulling up the web interface I am presented with the following. 

<img width="1770" alt="screen shot" src="https://user-images.githubusercontent.com/11856701/51994475-d7696a80-247e-11e9-9d0a-42c35926abda.png">
This is on a fresh install of Docker running on MacOS 10.14.3
I'm new to Docker and ELK so I'm a little stumped

**Comment by marco-lancini** [comment]
Hi @estoycon, can you please post here the container logs?

**Comment by marco-lancini** [comment]
Closing to due unresponsiveness
