### ISSUE TITLE
Couldn't find any Elasticsearch data

### ISSUE THREAD

**Issue by Hach0u** [marco-lancini/docker_offensive_elk#6]
Hi,

I've created successfully the index
`Invoke-WebRequest -Method PUT -Uri "http://localhost:9200/nmap-vuln-to-es"`

In Kibana, it's never detected. Do you have any idea why ? 
![image](https://user-images.githubusercontent.com/51485992/60344883-e4e83980-99b7-11e9-99df-be7072568e7d.png)

Elastiksearch container is started. I have the feeling that both containers can't speak to each other. Please note that I'm running it on Windows + Visual Studio code.

Thank you.

**Comment by marco-lancini** [comment]
Hi @Hach0u,
did you follow the updated [usage instructions](https://github.com/marco-lancini/docker_offensive_elk#usage) on the `README`?
Can you try, before creating an index, to ingest some data into Elasticsearch?

**Comment by Hach0u** [comment]
I followed from https://www.marcolancini.it/2018/blog-elk-for-nmap/. As you suggested, I'll ingest data first. Thanks for the prompt feedback.

**Comment by Hach0u** [comment]
Thanks a lot @marco-lancini. It's working fine now.
