### ISSUE TITLE
Help needed to setup the project

### ISSUE THREAD

**Issue by zfirered** [marco-lancini/docker_offensive_elk#7]
Every version i try non of them working
the problem is
from Kibana Server not ready and cannot connect to elastic search

i did everything like tutorial said but, non of them is working why??

**Comment by marco-lancini** [comment]
Hi @zfirered,
have you followed the instructions from the `README`?

Could you please post here every step you performed, and the error log?

**Comment by zfirered** [comment]
Im using kali linux or ubuntu still same issues

Start from scratch
Fresh install and already up to date

1. Install docker and docker-compose
2. Then i follow everything that README said
3. And the problem is elasticsearch not running on 9200 
There is no service elasticsearch that running on 9200 port

Is there something im missing?

And how to get the LOG ? So i can post the log here

Thanx anyway

**Comment by marco-lancini** [comment]
The [docker documentation](https://docs.docker.com/engine/reference/commandline/logs/) can help yo understand how to retrieve logs. Once pulled, please post them here so we can try troubleshoot

**Comment by zfirered** [comment]
Here the Log that i try to get it

root@kali:~/docker_offensive_elk# docker-compose up
Starting elk_elasticsearch ... done
Starting elk_ingestor      ... done
Starting elk_logstash      ... done
Starting elk_kibana        ... done
Attaching to elk_elasticsearch, elk_ingestor, elk_logstash, elk_kibana
elk_elasticsearch | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elk_ingestor     | Processing /data/*.xml file...
elk_ingestor     | Input file does not exist. Exiting.
elk_ingestor exited with code 0
elk_elasticsearch | {"type": "server", "timestamp": "2019-07-26T17:18:00,550+0000", "level": "WARN", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-cluster", "node.name": "b0c411be781f",  "message": "uncaught exception in thread [main]" , 
elk_elasticsearch | "stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "Caused by: org.elasticsearch.ElasticsearchException: failed to bind service",
elk_elasticsearch | "at org.elasticsearch.node.Node.<init>(Node.java:582) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "... 6 more",
elk_elasticsearch | "Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes",
elk_elasticsearch | "at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",
elk_elasticsearch | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
elk_elasticsearch | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]",
elk_elasticsearch | "at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]",
elk_elasticsearch | "at java.nio.file.Files.createDirectory(Files.java:692) ~[?:?]",
elk_elasticsearch | "at java.nio.file.Files.createAndCheckIsDirectory(Files.java:799) ~[?:?]",
elk_elasticsearch | "at java.nio.file.Files.createDirectories(Files.java:785) ~[?:?]",
elk_elasticsearch | "at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:270) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:207) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:267) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.node.Node.<init>(Node.java:272) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.1.1.jar:7.1.1]",
elk_elasticsearch | "... 6 more"] }
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:05Z","tags":["status","plugin:apm_oss@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:06Z","tags":["status","plugin:kibana@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:06Z","tags":["status","plugin:elasticsearch@undefined","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:06Z","tags":["status","plugin:console@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:06Z","tags":["status","plugin:interpreter@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:06Z","tags":["status","plugin:metrics@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:06Z","tags":["status","plugin:tile_map@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:07Z","tags":["status","plugin:timelion@undefined","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:07Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.19.0.2:9200"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:07Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:07Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elk_kibana       | {"type":"log","@timestamp":"2019-07-26T17:18:07Z","tags":["status","plugin:elasticsearch@undefined","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
elk_elasticsearch exited with code 1

**Comment by marco-lancini** [comment]
From the log I can see:

```
AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
```

Did you follow step 2 of the `README`?
In particular, you have to `chown` the `_data` folder:

```
sudo chown -R <user>:<user> ./_data/
```

**Comment by zfirered** [comment]
> From the log I can see:
> 
> ```
> AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
> ```
> 
> Did you follow step 2 of the `README`?
> In particular, you have to `chown` the `_data` folder:
> 
> ```
> sudo chown -R <user>:<user> ./_data/
> ```

yes, even i change to 1000:1000 the problem still exist

**Comment by zfirered** [comment]
the problem is not solved yet, please help me

**Comment by marco-lancini** [comment]
Elasticsearch fails to start as it does not have write access to the `_data/nodes` directory.
For this to work you need to ensure it has write access to it.

Try removing the `_data` folder, recreating it manually and re-assigning permissions.
A few pointers that might help you troubleshoot:
- Are you running docker as `root` or as a non privileged user?
- Ensure you use the correct ID (is `1000` your real ID)?
- An explanation of permissions with docker: https://medium.com/@nielssj/docker-volumes-and-file-system-permissions-772c1aee23ca

**Comment by zfirered** [comment]
> Elasticsearch fails to start as it does not have write access to the `_data/nodes` directory.
> For this to work you need to ensure it has write access to it.
> 
> Try removing the `_data` folder, recreating it manually and re-assigning permissions.
> A few pointers that might help you troubleshoot:
> 
> * Are you running docker as `root` or as a non privileged user?
> * Ensure you use the correct ID (is `1000` your real ID)?
> * An explanation of permissions with docker: https://medium.com/@nielssj/docker-volumes-and-file-system-permissions-772c1aee23ca
> 
> Also please refrain from creating multiple issues for the same problem.

already removing and create again
with user "root" or ID 0 ( kali )
or 1000 ( ubuntu )

ini kali yes im running on root

yeah sorry for that
